all: 
	pdflatex 2014-ieee-spoofing-temporal-cubes-double-col
	bibtex 2014-ieee-spoofing-temporal-cubes-double-col
	pdflatex 2014-ieee-spoofing-temporal-cubes-double-col

clean: 
	rm -f *.dvi *.log *.toc *.aux *.bbl *.blg *.loa *.los *.out *.cb 

cleanall:
	rm -f 2014-ieee-spoofing-temporal-cubes-double-col
